name: car_park
description: A simple and lightweight parking tracker.
version: 0.1.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.6.1
  flutter_svg: ^0.13.1
  flutter_duration_picker: ^1.0.4
  flutter_local_notifications: ^0.8.0
  auto_size_text: ^2.0.2
  localstorage: ^1.2.0
  url_launcher: ^5.1.0
  geolocator: ^5.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/languages/
  fonts:
    - family: handlee-regular
      fonts:
        - asset: assets/fonts/handlee-regular.ttf
